export const LOAD_TRANSLATION = "LOAD_TRANSLATION";
export const CHANGE_TO_ENGLISH = "CHANGE_TO_ENGLISH";
export const CHANGE_TO_ARABIC = "CHANGE_TO_ARABIC";

// PROFILE ACTIONS
export const UPDATE_PROFILE_NAME = "UPDATE_PROFILE_NAME";
export const UPDATE_PROFILE_EMAIL = "UPDATE_PROFILE_EMAIL";
export const UPDATE_PROFILE_MOBILE = "UPDATE_PROFILE_MOBILE";
export const UPDATE_PROFILE_PROFILE_MOBILE = "UPDATE_PROFILE_PROFILE_MOBILE";
export const UPDATE_PROFILE_ABOUT_AR = "UPDATE_PROFILE_ABOUT_AR";
export const UPDATE_PROFILE_ABOUT_EN = "UPDATE_PROFILE_ABOUT_EN";
export const UPDATE_PROFILE_STATUS = "UPDATE_PROFILE_STATUS";
export const UPDATE_PROFILE_STATUS_LABEL = "UPDATE_PROFILE_STATUS_LABEL";
export const UPDATE_PROFILE_LOCALE = "UPDATE_PROFILE_LOCALE";
export const UPDATE_PROFILE_AVATAR = "UPDATE_PROFILE_AVATAR";
export const UPDATE_COUNTRY_CITY = "UPDATE_COUNTRY_CITY";
export const UPDATE_PROFILE_PUSH_TOKEN = "UPDATE_PROFILE_PUSH_TOKEN";
export const UPDATE_PROFILE_UUID = "UPDATE_PROFILE_UUID";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";